#!/bin/bash

echo "Content-Type: application/json"
echo

cat << EOF
{
  "AUTH_TYPE": "${AUTH_TYPE}",
  "REMOTE_IDENT": "${REMOTE_IDENT}",
  "QUERY_STRIN": "${QUERY_STRIN}",
  "CONTENT_LENGTH": "${CONTENT_LENGTH}",
  "REMOTE_USER": "${REMOTE_USER}",
  "REMOTE_ADDR": "${REMOTE_ADDR}",
  "REMOTE_PORT": "${REMOTE_PORT}",
  "CONTENT_TYPE": "${CONTENT_TYPE}",
  "REQUEST_METHOD": "${REQUEST_METHOD}",
  "REMOTE_HOST": "${REMOTE_HOST}",
  "GATEWAY_INTERFACE": "${GATEWAY_INTERFACE}",
  "SCRIPT_NAME": "${SCRIPT_NAME}",
  "SERVER_PROTOCOL": "${SERVER_PROTOCOL}",
  "PATH_INFO": "${PATH_INFO}",
  "SERVER_NAME": "${SERVER_NAME}",
  "SERVER_SOFTWARE": "${SERVER_SOFTWARE}",
  "PATH_TRANSLATED": "${PATH_TRANSLATED}",
  "SERVER_PORT": "${SERVER_PORT}"
}
EOF

exit 0

